package org.example.trafficsim.signal;

import org.example.trafficsim.model.LaneDeclaration;
import org.example.trafficsim.model.LaneSignal;
import org.example.trafficsim.model.Movement;
import org.example.trafficsim.model.Road;

import java.util.*;
import java.util.stream.Collectors;

// Automatically generates signal phases from lane movement declarations.
//
// Algorithm:
//   1. Expands each LaneDeclaration into atomic LaneSignals (one per movement per lane).
//   2. Builds a conflict graph: vertices = LaneSignal, edges = signalsConflict(a, b).
//   3. Finds all maximal independent sets (Bron-Kerbosch on the conflict graph
//      = cliques of the complement graph).
//   4. Filters out redundant single-road sets and sets consisting solely of RIGHT
//      (omitted — RIGHT is by definition always permitted).
//   5. Each set → Phase with greenSignals and derived greenLaneIndices / greenRoads.
//
// Key difference from the old approach (lanesConflict):
//   Two signals from the same lane with different movements can now be placed in DIFFERENT phases.
//   Example: N lane0=[STRAIGHT, PERMISSIVE_LEFT] → signals N0-STRAIGHT and N0-PERMISSIVE_LEFT.
//   N0-STRAIGHT can be in the same phase as S0-STRAIGHT.
//   N0-PERMISSIVE_LEFT as well — because it does not conflict with SOUTH (opposite road).
//   But N0-PERMISSIVE_LEFT DOES CONFLICT with E0-STRAIGHT (perpendicular) → different set.
public class PhaseSetGenerator implements PhaseFactory {

    private final List<LaneDeclaration> declarations;
    private final PhaseTiming timing;

    public PhaseSetGenerator(List<LaneDeclaration> declarations, PhaseTiming timing) {
        this.declarations = List.copyOf(declarations);
        this.timing = timing;
    }

    // Default generator: 1 STRAIGHT lane per road, standard timing (1,5,1).
    // Produces exactly NS and EW phases.
    public static PhaseSetGenerator defaults() {
        List<LaneDeclaration> decls = new ArrayList<>();
        for (Road r : Road.values())
            decls.add(LaneDeclaration.defaultLane(r, 0));
        return new PhaseSetGenerator(decls, new PhaseTiming(1, 5, 1));
    }

    @Override
    public List<Phase> create() {
        // 1. Expand declarations into atomic signals
        List<LaneSignal> signals = expand(declarations);

        // 2. Bron-Kerbosch on independent sets (no conflicts)
        List<List<LaneSignal>> maximalSets = new ArrayList<>();
        bronKerbosch(new ArrayList<>(), new ArrayList<>(signals), new ArrayList<>(), maximalSets);

        // 3. Filter and convert to Phase objects
        List<Phase> phases = new ArrayList<>();
        int idx = 0;
        for (List<LaneSignal> set : maximalSets) {
            Set<Road> roads = set.stream().map(LaneSignal::road).collect(Collectors.toSet());
            // Filter out single-road sets (no value as a standalone phase)
            if (roads.size() < 2) continue;
            // Filter out sets consisting solely of RIGHT (always allowed; a dedicated phase is redundant)
            boolean allRight = set.stream().allMatch(s -> s.movement() == Movement.RIGHT);
            if (allRight) continue;

            phases.add(toPhase("p" + idx, set));
            idx++;
        }

        if (phases.isEmpty()) {
            throw new IllegalStateException("PhaseSetGenerator did not produce any phases — check laneDeclarations");
        }
        return Collections.unmodifiableList(phases);
    }

    // Expands a list of LaneDeclarations into a list of LaneSignals (1 per movement per lane).
    // RIGHT is excluded — it is always implicitly allowed in SimulationEngine
    // (does not conflict with anything), so it should not influence phase construction.
    // The result is sorted deterministically (road.ordinal, laneIndex, movement.ordinal)
    // so that the order of phases generated by Bron-Kerbosch is reproducible.
    private static List<LaneSignal> expand(List<LaneDeclaration> decls) {
        List<LaneSignal> result = new ArrayList<>();
        for (LaneDeclaration d : decls) {
            // Sort movements by ordinal so that iteration over Set<Movement> is deterministic
            List<Movement> sorted = d.movements().stream()
                    .filter(m -> m != Movement.RIGHT)
                    .sorted(Comparator.comparingInt(Enum::ordinal))
                    .toList();
            for (Movement m : sorted) {
                result.add(new LaneSignal(d.road(), d.index(), m));
            }
        }
        // Sort the full result: road → lane → movement
        result.sort(Comparator
                .comparingInt((LaneSignal s) -> s.road().ordinal())
                .thenComparingInt(LaneSignal::laneIndex)
                .thenComparingInt(s -> s.movement().ordinal()));
        return result;
    }

    // Bron-Kerbosch: finds all maximal independent sets in the conflict graph.
    private void bronKerbosch(List<LaneSignal> R,
                               List<LaneSignal> P,
                               List<LaneSignal> X,
                               List<List<LaneSignal>> results) {
        if (P.isEmpty() && X.isEmpty()) {
            results.add(new ArrayList<>(R));
            return;
        }
        for (int i = 0; i < P.size(); i++) {
            LaneSignal v = P.get(i);
            R.add(v);

            List<LaneSignal> newP = new ArrayList<>();
            for (LaneSignal u : P) {
                if (u != v && !ConflictMatrix.signalsConflict(v, u)) newP.add(u);
            }
            List<LaneSignal> newX = new ArrayList<>();
            for (LaneSignal u : X) {
                if (!ConflictMatrix.signalsConflict(v, u)) newX.add(u);
            }

            bronKerbosch(R, newP, newX, results);

            R.remove(R.size() - 1);
            P.remove(i);
            i--;
            X.add(v);
        }
    }

    // Converts a signal set into a Phase: greenSignals + derived greenRoads and greenLaneIndices
    private Phase toPhase(String id, List<LaneSignal> set) {
        Set<LaneSignal> immutableSignals = Set.copyOf(set);

        // Derived: greenRoads and greenLaneIndices (needed for backward-compat API)
        Map<Road, Set<Integer>> laneIndices = new LinkedHashMap<>();
        Set<Road> greenRoads = new LinkedHashSet<>();
        for (LaneSignal s : set) {
            greenRoads.add(s.road());
            laneIndices.computeIfAbsent(s.road(), r -> new LinkedHashSet<>()).add(s.laneIndex());
        }
        Map<Road, Set<Integer>> immutableLaneIndices = new LinkedHashMap<>();
        for (Map.Entry<Road, Set<Integer>> e : laneIndices.entrySet()) {
            immutableLaneIndices.put(e.getKey(), Set.copyOf(e.getValue()));
        }

        return new Phase(id, Set.copyOf(greenRoads), timing,
                Map.copyOf(immutableLaneIndices), immutableSignals);
    }
}

